### ISSUE TITLE
Add support for node colouring based on prefix

### ISSUE THREAD

**Issue by bbroeksema** [bbroeksema/silverbullet-graphview#4]
As a user, I want to color nodes differently based on prefix

E.g.
Resources/People/XXX -> Green
Resources/Organisations/YYY -> yellow
Project/ZZZ -> Blue

This must be implemented using the configuration system of @silverbulletmd as prefixes are completely user-specific.

Although, it would be nice to have some kind of color-picker, let's not complicate too much initially and use hex values.

**Comment by v411e** [comment]
I added a tag-based version of this in #13. This could easily be extended to work with page-names as well.
